In [333]:
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from torch.utils.data import Dataset

Loading the data

In [334]:
iris_csv = pd.read_csv('data\Iris\Iris.csv')

<>:1: SyntaxWarning: invalid escape sequence '\I'
<>:1: SyntaxWarning: invalid escape sequence '\I'
C:\Users\user\AppData\Local\Temp\ipykernel_6080\4241612236.py:1: SyntaxWarning: invalid escape sequence '\I'
  iris_csv = pd.read_csv('data\Iris\Iris.csv')


In [335]:
iris_csv[50:100]

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
50   51            7.0           3.2            4.7           1.4   
51   52            6.4           3.2            4.5           1.5   
52   53            6.9           3.1            4.9           1.5   
53   54            5.5           2.3            4.0           1.3   
54   55            6.5           2.8            4.6           1.5   
55   56            5.7           2.8            4.5           1.3   
56   57            6.3           3.3            4.7           1.6   
57   58            4.9           2.4            3.3           1.0   
58   59            6.6           2.9            4.6           1.3   
59   60            5.2           2.7            3.9           1.4   
60   61            5.0           2.0            3.5           1.0   
61   62            5.9           3.0            4.2           1.5   
62   63            6.0           2.2            4.0           1.0   
63   64            6.1           2.9            4.7           1.4   
64   65            5.6           2.9            3.6           1.3   
65   66            6.7           3.1            4.4           1.4   
66   67            5.6           3.0            4.5           1.5   
67   68            5.8           2.7            4.1           1.0   
68   69            6.2           2.2            4.5           1.5   
69   70            5.6           2.5            3.9           1.1   
70   71            5.9           3.2            4.8           1.8   
71   72            6.1           2.8            4.0           1.3   
72   73            6.3           2.5            4.9           1.5   
73   74            6.1           2.8            4.7           1.2   
74   75            6.4           2.9            4.3           1.3   
75   76            6.6           3.0            4.4           1.4   
76   77            6.8           2.8            4.8           1.4   
77   78            6.7           3.0            5.0           1.7   
78   79            6.0           2.9            4.5           1.5   
79   80            5.7           2.6            3.5           1.0   
80   81            5.5           2.4            3.8           1.1   
81   82            5.5           2.4            3.7           1.0   
82   83            5.8           2.7            3.9           1.2   
83   84            6.0           2.7            5.1           1.6   
84   85            5.4           3.0            4.5           1.5   
85   86            6.0           3.4            4.5           1.6   
86   87            6.7           3.1            4.7           1.5   
87   88            6.3           2.3            4.4           1.3   
88   89            5.6           3.0            4.1           1.3   
89   90            5.5           2.5            4.0           1.3   
90   91            5.5           2.6            4.4           1.2   
91   92            6.1           3.0            4.6           1.4   
92   93            5.8           2.6            4.0           1.2   
93   94            5.0           2.3            3.3           1.0   
94   95            5.6           2.7            4.2           1.3   
95   96            5.7           3.0            4.2           1.2   
96   97            5.7           2.9            4.2           1.3   
97   98            6.2           2.9            4.3           1.3   
98   99            5.1           2.5            3.0           1.1   
99  100            5.7           2.8            4.1           1.3   

            Species  
50  Iris-versicolor  
51  Iris-versicolor  
52  Iris-versicolor  
53  Iris-versicolor  
54  Iris-versicolor  
55  Iris-versicolor  
56  Iris-versicolor  
57  Iris-versicolor  
58  Iris-versicolor  
59  Iris-versicolor  
60  Iris-versicolor  
61  Iris-versicolor  
62  Iris-versicolor  
63  Iris-versicolor  
64  Iris-versicolor  
65  Iris-versicolor  
66  Iris-versicolor  
67  Iris-versicolor  
68  Iris-versicolor  
69  Iris-versicolor  
70  Iris-versicolor  
7

In [336]:
x =iris_csv[['SepalLengthCm',	'SepalWidthCm',	'PetalLengthCm',	'PetalWidthCm']]#get rid of id as it is just wasted compute

In [337]:
y = iris_csv['Species']
for index, i in enumerate(y):
    if i == 'Iris-setosa':
        y[index] = [1,0,0]
    if i == 'Iris-virginica':
        y[index] = [0,0,1]
    elif i == 'Iris-versicolor':
        y[index] = [0,1,0]

C:\Users\user\AppData\Local\Temp\ipykernel_6080\1798773714.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y[index] = [1,0,0]
C:\Users\user\AppData\Local\Temp\ipykernel_6080\1798773714.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y[index] = [1,0,0]
C:\Users\user\AppData\Local\Temp\ipykernel_6080\1798773714.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y[index] = [1,0,0]
C:\Users\user\AppData\Local\Temp\ipykernel_6080\1

In [338]:
y

0      [1, 0, 0]
1      [1, 0, 0]
2      [1, 0, 0]
3      [1, 0, 0]
4      [1, 0, 0]
         ...    
145    [0, 0, 1]
146    [0, 0, 1]
147    [0, 0, 1]
148    [0, 0, 1]
149    [0, 0, 1]
Name: Species, Length: 150, dtype: object

In [339]:
import numpy as np
# let's turn the labels into classes

In [340]:
y = torch.tensor(y)
x= torch.tensor(np.array(x))

In [341]:
x.dtype
x =x.to(torch.float32)

In [342]:
model = nn.Sequential(nn.Linear(4, 10),
                      nn.ReLU(),
                      nn.Linear(10,3))
print(x.dtype, x.shape)
model(x)

torch.float32 torch.Size([150, 4])


tensor([[-8.8399e-02, -3.2631e-02,  1.8964e-01],
        [-5.6592e-02, -4.1240e-02,  1.4472e-01],
        [-6.9954e-02, -6.1758e-02,  1.4540e-01],
        [-2.4487e-02, -6.9206e-02,  1.2554e-01],
        [-8.6219e-02, -4.3024e-02,  1.8836e-01],
        [-5.7654e-02, -4.4325e-03,  1.7521e-01],
        [-4.8190e-02, -6.9157e-02,  1.2147e-01],
        [-6.0654e-02, -3.9813e-02,  1.7302e-01],
        [-2.2165e-02, -8.2766e-02,  1.0201e-01],
        [-4.8573e-02, -4.8248e-02,  1.7299e-01],
        [-9.6822e-02, -1.0419e-02,  2.2050e-01],
        [-3.0729e-02, -5.7387e-02,  1.5512e-01],
        [-5.6273e-02, -5.4893e-02,  1.6285e-01],
        [-7.8934e-02, -9.7356e-02,  1.3590e-01],
        [-1.8616e-01,  1.9778e-02,  2.7769e-01],
        [-1.3101e-01,  1.3364e-02,  2.3394e-01],
        [-1.2854e-01, -3.3618e-03,  1.8816e-01],
        [-8.2617e-02, -2.7631e-02,  1.6418e-01],
        [-7.7819e-02,  1.8266e-02,  2.1662e-01],
        [-7.6657e-02, -3.3117e-02,  1.7910e-01],
        [-4.9614e-02

In [343]:
loss_fn = nn.CrossEntropyLoss()
optim = torch.optim.Adam(model.parameters(),lr=0.01)

In [344]:
x.shape
y.shape #so to have the same inner shapes

torch.Size([150, 3])

In [345]:
y=y.argmax(dim=1) #gets the indice of the correct label

In [346]:
train_data = DataLoader(TensorDataset(x,y), shuffle=True, batch_size=5)#put our dataset with specifying what are the inputs and outputs

In [347]:
next(iter(train_data))

[tensor([[4.9000, 2.4000, 3.3000, 1.0000],
         [6.7000, 3.0000, 5.2000, 2.3000],
         [5.9000, 3.0000, 4.2000, 1.5000],
         [4.6000, 3.6000, 1.0000, 0.2000],
         [5.0000, 3.4000, 1.6000, 0.4000]]),
 tensor([1, 2, 1, 0, 0])]

In [348]:
import matplotlib.pyplot as plt

In [366]:
for idx, idy in train_data:
    output = model(idx)
    loss = loss_fn(output, idy)#loss takes the index of the class only
    print('loss is ', loss)
    optim.zero_grad()
    loss.backward()
    optim.step()

loss is  tensor(0.2848, grad_fn=<NllLossBackward0>)
loss is  tensor(0.0781, grad_fn=<NllLossBackward0>)
loss is  tensor(0.0428, grad_fn=<NllLossBackward0>)
loss is  tensor(0.0061, grad_fn=<NllLossBackward0>)
loss is  tensor(0.0208, grad_fn=<NllLossBackward0>)
loss is  tensor(0.0258, grad_fn=<NllLossBackward0>)
loss is  tensor(0.3060, grad_fn=<NllLossBackward0>)
loss is  tensor(0.0162, grad_fn=<NllLossBackward0>)
loss is  tensor(0.0707, grad_fn=<NllLossBackward0>)
loss is  tensor(0.0733, grad_fn=<NllLossBackward0>)
loss is  tensor(0.2883, grad_fn=<NllLossBackward0>)
loss is  tensor(0.2697, grad_fn=<NllLossBackward0>)
loss is  tensor(0.1730, grad_fn=<NllLossBackward0>)
loss is  tensor(0.1022, grad_fn=<NllLossBackward0>)
loss is  tensor(0.1028, grad_fn=<NllLossBackward0>)
loss is  tensor(0.0125, grad_fn=<NllLossBackward0>)
loss is  tensor(0.0361, grad_fn=<NllLossBackward0>)
loss is  tensor(0.0151, grad_fn=<NllLossBackward0>)
loss is  tensor(0.0818, grad_fn=<NllLossBackward0>)
loss is  ten

In [ ]:
model(x[120])
#it got it right, data is a bit small though

tensor([-5.4112,  3.4186,  5.2137], grad_fn=<ViewBackward0>)

In [368]:
iris_csv[:int(150*0.8)]
iris_csv[int(150*0.8):]
#the data is ordered, gotta randomize it

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm    Species
120  121            6.9           3.2            5.7           2.3  [0, 0, 1]
121  122            5.6           2.8            4.9           2.0  [0, 0, 1]
122  123            7.7           2.8            6.7           2.0  [0, 0, 1]
123  124            6.3           2.7            4.9           1.8  [0, 0, 1]
124  125            6.7           3.3            5.7           2.1  [0, 0, 1]
125  126            7.2           3.2            6.0           1.8  [0, 0, 1]
126  127            6.2           2.8            4.8           1.8  [0, 0, 1]
127  128            6.1           3.0            4.9           1.8  [0, 0, 1]
128  129            6.4           2.8            5.6           2.1  [0, 0, 1]
129  130            7.2           3.0            5.8           1.6  [0, 0, 1]
130  131            7.4           2.8            6.1           1.9  [0, 0, 1]
131  132            7.9           3.8            6.4           2.0  [0, 0, 1]
132  133            6.4           2.8            5.6           2.2  [0, 0, 1]
133  134            6.3           2.8            5.1           1.5  [0, 0, 1]
134  135            6.1           2.6            5.6           1.4  [0, 0, 1]
135  136            7.7           3.0            6.1           2.3  [0, 0, 1]
136  137            6.3           3.4            5.6           2.4  [0, 0, 1]
137  138            6.4           3.1            5.5           1.8  [0, 0, 1]
138  139            6.0           3.0            4.8           1.8  [0, 0, 1]
139  140            6.9           3.1            5.4           2.1  [0, 0, 1]
140  141            6.7           3.1            5.6           2.4  [0, 0, 1]
141  142            6.9           3.1            5.1           2.3  [0, 0, 1]
142  143            5.8           2.7            5.1           1.9  [0, 0, 1]
143  144            6.8           3.2            5.9           2.3  [0, 0, 1]
144  145            6.7           3.3            5.7           2.5  [0, 0, 1]
145  146            6.7           3.0            5.2           2.3  [0, 0, 1]
146  147            6.3           2.5            5.0           1.9  [0, 0, 1]
147  148            6.5           3.0            5.2           2.0  [0, 0, 1]
148  149            6.2           3.4            5.4           2.3  [0, 0, 1]
149  150            5.9           3.0            5.1           1.8  [0, 0, 1]